[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rdev = "0.5.3"
screenshots = "0.8.3"
tray-icon = "0.9.0"

[target.'cfg(target_os = "windows")'.dependencies]
winit = "0.28"
winapi = { version = "0.3", features = ["winuser", "errhandlingapi", "processthreadsapi"] }
